name: Apply Database Migration

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "APPLY" to confirm migration'
        required: true
        default: ''

jobs:
  apply-migration:
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm == 'APPLY'

    steps:
    - uses: actions/checkout@v3

    - name: Setup Supabase CLI
      uses: supabase/setup-cli@v1
      with:
        version: latest

    - name: Check and Apply Migrations
      env:
        SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
        PGPASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
      run: |
        echo "Checking migration status..."

        # Apply each migration file individually using psql
        for migration in supabase/migrations/*.sql; do
          filename=$(basename "$migration" .sql)
          echo "Checking migration: $filename"

          # Check if migration is already applied
          result=$(psql -h aws-0-ap-southeast-2.pooler.supabase.com -p 6543 \
            -U postgres.bqvptfdxnrzculgjcnjo -d postgres -t -c \
            "SELECT version FROM supabase_migrations.schema_migrations WHERE version = '$filename';")

          if [ -z "$result" ]; then
            echo "Applying migration: $filename"
            psql -h aws-0-ap-southeast-2.pooler.supabase.com -p 6543 \
              -U postgres.bqvptfdxnrzculgjcnjo -d postgres -f "$migration"

            # Record migration in schema_migrations table
            psql -h aws-0-ap-southeast-2.pooler.supabase.com -p 6543 \
              -U postgres.bqvptfdxnrzculgjcnjo -d postgres -c \
              "INSERT INTO supabase_migrations.schema_migrations (version, name) VALUES ('$filename', '$filename');"
          else
            echo "Migration already applied: $filename"
          fi
        done

        echo "✅ All migrations checked/applied successfully!"

    - name: Create Storage Bucket
      env:
        SUPABASE_URL: https://bqvptfdxnrzculgjcnjo.supabase.co
        SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxdnB0ZmR4bnJ6Y3VsZ2pjbmpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMjY5NDAsImV4cCI6MjA2OTgwMjk0MH0.I10e1TQkVntpEm3KSXmydNJQLbhJQ3MU4SyMt1lOvOk
      run: |
        echo "✅ Migration applied successfully!"
        echo ""
        echo "Next step: Create storage bucket 'documents' manually in Supabase Dashboard"
        echo "https://supabase.com/dashboard/project/bqvptfdxnrzculgjcnjo/storage/buckets"
